### ISSUE TITLE
Possible Issue at Branch and Jump Unit

### ISSUE THREAD

**Issue by IsuruLakshan97** [cepdnaclk/e16-co502-RISCV-Pipeline-CPU-Implimentation-Group2#5]
@Randikaviraj 
Hi Randika,
I think in the branch and Jump unit, the output signal to the PC mux (branch_jump_mux_signal) should be set to 0 specifically.
otherwise, it would be set to 'don't care' at the beginning and the pc mux may not fetch the correct PC for the next instructions.

**Comment by Randikaviraj** [comment]
@IsuruLakshan97 
Hi Isuru,
You are correct, that issue will effect the system. Possible solution would be add the RESET signal to the pipeline registers and reset pipeline register values to 0v

**Comment by IsuruLakshan97** [comment]
Yeah!! thanks for the consideration, that solved issue
